name: Build Web font

defaults:
  run:
    shell: bash # Enable bash pipefail option to watch pipe errors

on:
  workflow_dispatch: # Execute manually

jobs:
  webfont-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Prepare Python env
      - name: Prepare requirements.txt
        if: hashFiles('**/requirements.txt', '**/pyproject.toml') == ''
        run: |
          touch ./requirements.txt
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip  # Enable cache
      # Checkout this repo codes
      - name: Checkout this repo code
        uses: actions/checkout@v4
      # Clear dist folder
      - name: Clear dist folder
        run: rm -rf ./dist/ && chmod 777 ./*.sh
      # Build Web font
      - name: Build Web font
        run: ./build_woff2.sh color
